import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef } from 'react'
import { MdClose } from 'react-icons/md'
import { toast } from 'react-toastify'

import Button from '@components/Button'
import Footer from '@components/Footer'
import Modal, { ModalRef } from '@components/Modal'
import {
	Container,
	Card,
	Description,
	Grid,
	Main,
	Title,
	ModalContent,
	ButtonsWrapper,
} from '@styles/pages/Home'

const Home: NextPage = () => {
	const modalRef = useRef<ModalRef>({
		close: () => {
			return null
		},
		open: () => {
			return null
		},
	})

	return (
		<Container>
			<Head>
				<title>Next/src/pages/src/pages</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<Modal ref={modalRef}>
					<ModalContent>
						<p>Hello World! I&apos;m a Modal Component!</p>

						<div className="buttons">
							<Button
								onClick={() => modalRef.current.close()}
								padding=".75rem 2rem"
								pointer
								bgColor="red"
							>
								Close <MdClose size={20} style={{ marginLeft: '.5rem' }} />
							</Button>
						</div>
					</ModalContent>
				</Modal>

				<Title>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</Title>

				<Description>
					Get started by editing <code>pages/index.tsx</code>
				</Description>

				<ButtonsWrapper>
					<Button onClick={() => modalRef.current.open()} pointer>
						Try opening modal
					</Button>
					<Button
						onClick={() =>
							toast.info("I'm a toast :D", {
								position: 'top-right',
								autoClose: 5000,
								hideProgressBar: false,
								closeOnClick: true,
								pauseOnHover: true,
								draggable: true,
							})
						}
						pointer
						inverted
					>
						Try opening toast
					</Button>
				</ButtonsWrapper>

				<Grid>
					<Card href="https://nextjs.org/docs">
						<h2>Documentation &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</Card>

					<Card href="https://nextjs.org/learn">
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</Card>

					<Card href="https://github.com/vercel/next.js/tree/canary/examples">
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</Card>

					<Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</Card>
				</Grid>
			</Main>

			<Footer />
		</Container>
	)
}

export default Home
