import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import StepWizard from 'react-step-wizard'

import StepOne from '@/steps/StepOne'
import StepTwo from '@/steps/StepTwo'
import { Container, Main } from '@styles/pages/Steps'

const Steps: NextPage = () => {
	return (
		<Container>
			<Head>
				<title>Steps</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main>
				<h1>Usando steps!</h1>
				<StepWizard className="wizard">
					<StepOne />
					<StepTwo />
				</StepWizard>
			</Main>
		</Container>
	)
}

export default Steps
